Eigenvectors and Eigenvalues

An eigenvector (eigen is German for "typical"; we could translate eigenvector to "characteristic vector") is a special vector 'v' such that when it is transformed by some matrix (let's say 'A'), the product 'Av' has the exact same direction as 'v'.

An eigenvalue is a scalar (traditionally represented as 'λ') that simply scales the eigenvector 'v' such that the following equation is satisfied:

Av = λv


In [108]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [109]:
A = np.array([[-1, 4], [2, -2]])

In [110]:
λ, vectors = np.linalg.eig(A)
print(λ)
print(vectors)

[ 1.37228132 -4.37228132]
[[ 0.86011126 -0.76454754]
 [ 0.51010647  0.64456735]]


In [111]:
v = np.array([ 0.86011126,  0.51010647])

In [112]:
np.dot(A, v)

array([1.18031462, 0.70000958])

In [ ]:
v * λ[0]

array([1.18031462, 0.70000958])

In [114]:
A = torch.tensor([[-1, 4], [2, -2.]])

In [115]:
eigens = torch.linalg.eig(A)
eigens

torch.return_types.linalg_eig(
eigenvalues=tensor([ 1.3723+0.j, -4.3723+0.j]),
eigenvectors=tensor([[ 0.8601+0.j, -0.7645+0.j],
        [ 0.5101+0.j,  0.6446+0.j]]))

In [116]:
# torch.matmul(A, eigens.eigenvectors[:, 0])

LETS TRY WITH 3 VALUES

In [117]:
A = np.array([[25, 2, 9], [5, 26, -5], [3, 7, -1]])

In [118]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [119]:
eigenvalues

array([29.67623202, 20.62117365, -0.29740567])

In [120]:
eigenvectors

array([[-0.71175736, -0.6501921 , -0.34220476],
       [-0.66652125,  0.74464056,  0.23789717],
       [-0.22170001,  0.15086635,  0.90901091]])

In [121]:
eivector = eigenvectors[:, 0]
eivector

array([-0.71175736, -0.66652125, -0.22170001])

In [123]:
np.dot(A, eivector) * (1/eigenvalues[0])

array([-0.71175736, -0.66652125, -0.22170001])