In [1]:
import torch

In [3]:
A = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
A

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [5]:
lambdas, V = torch.linalg.eig(A)
V

tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
        [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
        [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]])

In [6]:
V_inv = torch.linalg.inv(V)

In [9]:
A_calc = torch.matmul(V, torch.matmul(torch.diag(lambdas), V_inv))
A_calc

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 3.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [ 5.0000+0.j,  7.0000+0.j,  4.0000+0.j]])

In [ ]:
# An example of eigenvector matrix being symmetric
A = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
A

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [13]:
lambdas, V = torch.linalg.eig(A)
V

tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
        [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
        [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]])

In [14]:
V_inv = torch.linalg.inv(V)
V_inv

tensor([[ 0.9744+0.j,  0.0614+0.j, -0.2163+0.j],
        [ 0.1943+0.j,  0.2548+0.j,  0.9473+0.j],
        [-0.1132+0.j,  0.9651+0.j, -0.2363+0.j]])

In [16]:
A_calc = torch.matmul(V, torch.matmul(torch.diag(lambdas), V_inv))
A_calc

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 2.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [-5.0000+0.j,  1.0000+0.j,  4.0000+0.j]])