In [1]:
import numpy as np
import torch

In [2]:
A = np.array([[-1, 2], [3, -2], [5, 7]])

In [3]:
U, d, VT = np.linalg.svd(A)

In [4]:
print(U)
print(d)
print(VT)

[[ 0.12708324  0.47409506  0.87125411]
 [ 0.00164602 -0.87847553  0.47778451]
 [ 0.99189069 -0.0592843  -0.11241989]]
[8.66918448 4.10429538]
[[ 0.55798885  0.82984845]
 [-0.82984845  0.55798885]]


In [ ]:
#This gives error because the dimensions don't match, so we will extend the diagonal singular value matrix with 0s. 
A_calc = np.matmul(U, np.matmul(np.diag(d), VT))
A_calc

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [9]:
D = np.concatenate((np.diag(d), [[0, 0]]), axis = 0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [11]:
A_calc = np.matmul(U, np.matmul(D, VT))
A_calc

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

In [12]:
A = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
A

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [13]:
U, d, VT = np.linalg.svd(A)

In [14]:
display(U, d, VT)

array([[-0.9757195 , -0.1822729 , -0.1214413 ],
       [-0.09750433, -0.1350092 ,  0.9860352 ],
       [-0.19612318,  0.9739348 ,  0.11395871]], dtype=float32)

array([26.163235,  8.187547,  2.539532], dtype=float32)

array([[-0.98099935, -0.11960649,  0.15275636],
       [-0.01125803,  0.8211271 ,  0.5706343 ],
       [ 0.19368395, -0.55807215,  0.8068718 ]], dtype=float32)

In [16]:
A_calc = np.matmul(U, np.matmul(np.diag(d), VT))
A_calc

array([[25.       ,  1.9999999, -5.       ],
       [ 2.9999998, -2.0000002,  1.       ],
       [ 5.       ,  7.       ,  3.9999998]], dtype=float32)