In [32]:
import numpy as np
import torch

In [33]:
A = np.array([[-1, 2], [3, -2], [5, 7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [34]:
U, d, VT = np.linalg.svd(A)
display(U, d, VT)

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

array([8.66918448, 4.10429538])

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [35]:
D = np.diag(d)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [36]:
D_plus = np.linalg.inv(D)
D_plus

array([[0.1153511 , 0.        ],
       [0.        , 0.24364718]])

In [37]:
D_plus = np.concatenate((D_plus, np.array([[0, 0]]).T), axis = 1)
D_plus

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364718, 0.        ]])

In [38]:
A_plus = np.matmul(VT.T, np.matmul(D_plus, U.T))
A_plus

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

In [39]:
np.linalg.pinv(A)

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])