In [1]:
import torch
import tensorflow as tf
import numpy as np

SCALAR TENSORS

In [4]:
x_pt = torch.tensor(25, dtype=torch.int32)
x_pt.shape

torch.Size([])

In [5]:
x_tf = tf.Variable(25, dtype = tf.int32)
y_tf = tf.Variable(3, dtype = tf.int32)

In [6]:
tf.add(x_tf, y_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=28>

In [7]:
x_tf_float = tf.Variable(23.33, dtype = tf.float32)
x_tf_float

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=23.329999923706055>

VECTOR TENSORS

In [8]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [9]:
np.array([1, 2, 3], dtype = np.float16)

array([1., 2., 3.], dtype=float16)

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros(3, dtype = np.int16)

array([0, 0, 0], dtype=int16)

In [12]:
np.array([1, 2, 3]).shape

(3,)

In [13]:
# transpose of a vector(1d array) has no effect on shape or anything
a_t = a.T
a_t.shape

(3,)

In [14]:
new_a = np.array([[1, 2, 3]])
new_a

array([[1, 2, 3]])

In [15]:
new_a.T

array([[1],
       [2],
       [3]])

In [16]:
print(new_a.shape, new_a.T.shape)

(1, 3) (3, 1)


In [17]:
a_torch = torch.tensor([1, 2, 3], dtype = torch.int32)
a_tf = tf.Variable([1, 2, 3], dtype = np.int16)
print(a_torch)
print(a_tf)

tensor([1, 2, 3], dtype=torch.int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int16, numpy=array([1, 2, 3], dtype=int16)>


MATRIX TENSORS

In [18]:
a_np = np.array([[1, 2], [3, 4], [5, 6]], dtype = np.float16)
a_pt = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype = torch.float16)
a_tf = tf.Variable([[1, 2], [3, 4], [5, 6]], dtype = tf.float16)

In [19]:
a_np.shape

(3, 2)

In [21]:
print(a_np.size) #size and len give different values, size tells all the elements inside the matrix or array
print(len(a_np))#unlike len which gives size of the outer array only

6
3


In [23]:
a_np[:, 1]

array([2., 4., 6.], dtype=float16)

In [24]:
a_np[2, :]

array([5., 6.], dtype=float16)

In [26]:
a_np[0:2, 0:2]

array([[1., 2.],
       [3., 4.]], dtype=float16)

In [27]:
tf.rank(a_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [28]:
tf.shape(a_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

RANK 4 TENSORS

In [32]:
rank4_arr_np = np.zeros([32, 28, 28, 3])
rank4_arr_np

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [35]:
rank4_arr_tf = tf.zeros([32, 28, 28, 3])
rank4_arr_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

In [36]:
tf.shape(rank4_arr_tf)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([32, 28, 28,  3])>