In [33]:
import numpy as np
import tensorflow as tf
import torch

In [34]:
arr_np = np.array([[1, 2], [3, 4], [5, 6]])
arr_th = torch.tensor([[1, 2], [3, 4], [5, 6]])
arr_tf = tf.Variable([[1, 2], [3, 4], [5, 6]])
print(arr_np)
print(arr_th)
print(arr_tf)

[[1 2]
 [3 4]
 [5 6]]
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>


TENSOR TRANSPOSE

In [35]:
arr_np.T

array([[1, 3, 5],
       [2, 4, 6]])

In [36]:
arr_th.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [37]:
tf.transpose(arr_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

HADAMARD PRODUCT

In [38]:
#Hadamard Product
#works just like this for tensorflow and pytorch
arr_np*arr_np

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [39]:
arr_np+2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [40]:
arr_np+arr_np

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

TENSOR REDUCTION TOWARDS ROWS OR COLUMNS

In [41]:
print(arr_np.sum(axis=0))
print(torch.sum(arr_th, 0))
print(tf.reduce_sum(arr_tf, axis = 0))

[ 9 12]
tensor([ 9, 12])
tf.Tensor([ 9 12], shape=(2,), dtype=int32)


In [42]:
# more operation like this available
# maximum
# minimum
# mean
# etc

DOT PRODUCT

In [43]:
vec_np = np.array([1, 5, 0])
vec_np2 = np.array([5, 7, 2])

np.dot(vec_np, vec_np2)

40

In [44]:
np.dot(arr_np, arr_np.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

MATRIX INVERSION

In [45]:
arr_np = np.array([[1, 2], [3, 4.]])
arr_np_inv = np.linalg.inv(arr_np)

In [46]:
y = np.array([17, 21])
y

array([17, 21])

In [47]:
np.dot(arr_np_inv, y)

array([-13.,  15.])

In [50]:
print(torch.inverse(torch.from_numpy(arr_np)))
print(tf.linalg.inv(tf.convert_to_tensor(arr_np)))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]], dtype=torch.float64)
tf.Tensor(
[[-2.   1. ]
 [ 1.5 -0.5]], shape=(2, 2), dtype=float64)
