FORBINIUS NORM

In [30]:
import numpy as np
import torch
import tensorflow as tf

In [31]:
arr_np = np.array([[1, 2], [3, 4]])
arr_th = torch.tensor([[1, 2], [3, 4.]])
arr_tf = tf.Variable([[1, 2], [3, 4.]])

In [32]:
np.linalg.norm(arr_np)

5.477225575051661

In [33]:
torch.norm(arr_th)

tensor(5.4772)

In [34]:
tf.norm(arr_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.4772257804870605>

MATRIX MULTIPLICATION

In [35]:
arr1_np = np.array([[1, 2], [3, 4], [5, 6]])
arr2_np = np.array([[1, 9], [2, 0]])

np.dot(arr1_np, arr2_np)

array([[ 5,  9],
       [11, 27],
       [17, 45]])

In [36]:
arr1_th = torch.from_numpy(arr1_np)
arr2_th = torch.from_numpy(arr2_np)

torch.matmul(arr1_th, arr2_th)

tensor([[ 5,  9],
        [11, 27],
        [17, 45]], dtype=torch.int32)

In [37]:
arr1_tf = tf.convert_to_tensor(arr1_np)
arr2_tf = tf.convert_to_tensor(arr2_np)

tf.matmul(arr1_tf, arr2_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [11, 27],
       [17, 45]])>

In [38]:
# suppose if arr2 in a vector in arr

arr2_tf = tf.Variable([1, 2])

tf.(arr1_tf, arr2_tf) 

SyntaxError: invalid syntax (4028439345.py, line 5)